### ISSUE TITLE
CSS values being set as NaNpx

### ISSUE THREAD

**Issue by sidhuko** [shakyShane/gulp-svg-sprites#29]
For some reason the CSS output is returning NaNpx, like below

``` css
.action-voted {
    width: NaNpx;
    height: NaNpx;
    background-position: -NaNpx 0;
}
```
