### ISSUE TITLE
Prevent PNG fallback being added to the CSS file

### ISSUE THREAD

**Issue by adam-lynch** [shakyShane/gulp-svg-sprites#63]
Not a big deal but I just noticed the following in the resultant CSS:

``` css
.no-svg .icon:before {
  background-image: url("../spritesheet.png");
}
```

I don't need any PNG fallback. I didn't see any option to disable this.

---

Out of curiousity, if I was using a PNG fallback, shouldn't it be possible to customize this bit of CSS? `.no-svg` looks like a class that Modernizr would add.
