### ISSUE TITLE
Escape Less variables in templates

### ISSUE THREAD

**Issue by AlexandreBroudin** [shakyShane/gulp-svg-sprites#66]
I have this this kind of CSS template

``` CSS
.{common} {
    vertical-align:middle;
    display: inline-block;
    background-image: url('/frontend/core/images/pictos.svg?v=@{cacheVersion}');
    background-repeat: no-repeat;
    background-size: {relWidth} * 10px;
}
```

How can I escape Less/Sass variables ?
